/**
 * USTED Kumasi academic catalogue seed
 * Academic year source: 2026/2027 official USTED admissions publications.
 *
 * IMPORTANT:
 * - This intentionally excludes all programmes listed after the source documents switch
 *   to "ASANTE-MAMPONG CAMPUS".
 * - "Courses" here means selectable academic programmes for onboarding. The admissions
 *   publications do not provide semester-by-semester course-unit/module lists.
 *
 * Expected Prisma model shape is provided in `academic-programme.schema.prisma`.
 */

import "dotenv/config";
import { db } from "../src/lib/db";

export const USTED_KUMASI_PROGRAMMES = [
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Construction Technology and Management with Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 1,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Wood Technology with Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 2,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Welding and Fabrication Engineering Technology with Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 3,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Plumbing and Gas Technology",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 4,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Applied Technology (Building Construction and Wood)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 5,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Design and Communication Technology",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 6,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Construction Technology",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 7,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Architecture and Digital Construction",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 8,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Wood Technology",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 9,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Welding and Fabrication Technology",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 10,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Mechanical Engineering Technology Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 11,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Mechanical Engineering Technology",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 12,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Automotive Engineering Technology Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 13,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Electrical and Electronics Engineering with Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 14,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Electrical and Electronics Engineering",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 15,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Civil Engineering",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 16,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Biomedical Equipment Engineering",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 17,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Sc. Renewable Energy Engineering with Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 18,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Ed. Applied Technology (Electrical and Electronics)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 19,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Ed. Applied Technology (Automotive and Mechanical)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 20,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Ed. STEM (Engineering with Biomedical Science)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 21,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Ed. STEM (Engineering with Manufacturing)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 22,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "B.Ed. STEM (Engineering with Robotics)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 23,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Automotive Technology",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 24,
},
{
  academicUnit: "Faculty of Engineering and Technology",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Mechanical Technology",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 25,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Fashion Design and Textiles Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 26,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Catering and Hospitality Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 27,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Art and Design Technology",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 28,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Home Economics (Clothing and Textiles)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 29,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Home Economics (Food and Nutrition)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 30,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Fashion Design and Textiles",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 31,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Catering and Hospitality",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 32,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Information Technology",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 33,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Cyber Security and Digital Forensics",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 34,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Statistical Computing",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 35,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Mathematics",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 36,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Computing with Artificial Intelligence (AI)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 37,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Computing with Internet of Things (IOT)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 38,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Information Technology",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 39,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Mathematics",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME", "WEEKEND", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 40,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Cyber Security and Digital Forensics",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 41,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "2-year Diploma in Information Technology",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 42,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. English",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 43,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. French",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 44,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. Arabic",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 45,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. Social Studies",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 46,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. Geography",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 47,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. Ghanaian Language (Asante Twi)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 48,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. Early Grade",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 49,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. Upper Primary",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 50,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "B.Ed. Physical Education and Health",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 51,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "Postgraduate Diploma in Education (PGDE)",
  studyLevel: "POSTGRADUATE",
  awardType: "POSTGRADUATE_DIPLOMA",
  studyModes: ["FULL_TIME", "SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 52,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Accounting",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 53,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Procurement and Supply Chain Management",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 54,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Banking and Finance",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 55,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Business Information Systems",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 56,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Marketing",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 57,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Economics with Social Studies",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 58,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.B.A. Management",
  studyLevel: "UNDERGRADUATE",
  awardType: "BBA",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 59,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Business Studies (Accounting)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 60,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Business Studies (Management)",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 61,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Ed. Economics",
  studyLevel: "UNDERGRADUATE",
  awardType: "BED",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 62,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "B.Sc. Economics",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 63,
},
{
  academicUnit: "Institute of Entrepreneurial Development Education and Innovation",
  academicUnitType: "INSTITUTE",
  name: "B.Sc. Entrepreneurship Education",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 64,
},
{
  academicUnit: "Institute of Entrepreneurial Development Education and Innovation",
  academicUnitType: "INSTITUTE",
  name: "B.Sc. Marketing and Entrepreneurship",
  studyLevel: "UNDERGRADUATE",
  awardType: "BSC",
  studyModes: ["FULL_TIME"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 65,
},
{
  academicUnit: "Institute for Competency-Based Training and Research",
  academicUnitType: "INSTITUTE",
  name: "Diploma in Education, Competency-Based Training (CBT)",
  studyLevel: "DIPLOMA",
  awardType: "DIPLOMA",
  studyModes: ["SANDWICH", "WEEKEND"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Undergraduate_Programmes_2026-2027.pdf",
  sortOrder: 66,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "PhD Educational Leadership",
  studyLevel: "POSTGRADUATE",
  awardType: "PHD",
  studyModes: ["FULL_TIME"],
  durationYears: 3,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 67,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M. Phil. English",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 68,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M. Phil. Educational Leadership (Curriculum Development option)",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 69,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M. Phil. Educational Leadership (Instructional Design and Technology option)",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 70,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M. Phil. Educational Leadership (Organisational Behaviour and Management Education option)",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 71,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M. Phil. in Teaching and Learning",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 72,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M.A. Educational Leadership (Curriculum option)",
  studyLevel: "POSTGRADUATE",
  awardType: "MA",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 73,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M.A. Educational Leadership (Educational Technology option)",
  studyLevel: "POSTGRADUATE",
  awardType: "MA",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 74,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "M.A. Educational Leadership (Organisational Behaviour and Management in Education option)",
  studyLevel: "POSTGRADUATE",
  awardType: "MA",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 75,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "Postgraduate Diploma in Teaching and Learning in Higher Education",
  studyLevel: "POSTGRADUATE",
  awardType: "POSTGRADUATE_DIPLOMA",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 76,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "Postgraduate Diploma in Professional Educational Leadership (PGDEL)",
  studyLevel: "POSTGRADUATE",
  awardType: "POSTGRADUATE_DIPLOMA",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 77,
},
{
  academicUnit: "Faculty of Education and Communication Sciences",
  academicUnitType: "FACULTY",
  name: "National Professional Education Leadership Qualifications (NPELQF)",
  studyLevel: "POSTGRADUATE",
  awardType: "PROFESSIONAL",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 78,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "PhD Wood Science and Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "PHD",
  studyModes: ["FULL_TIME"],
  durationYears: 3,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 79,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "PhD Construction Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "PHD",
  studyModes: ["FULL_TIME"],
  durationYears: 3,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 80,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "PhD Construction Management",
  studyLevel: "POSTGRADUATE",
  awardType: "PHD",
  studyModes: ["FULL_TIME"],
  durationYears: 3,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 81,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Wood Science and Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 82,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Construction Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 83,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Construction Management",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 84,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Electrical Power Systems Engineering",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 85,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M.Phil. Mechanical Engineering Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 86,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Automotive Engineering Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 87,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Wood Science and Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 88,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Construction Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 89,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Construction Management",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 90,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Electrical and Electronics Engineering",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 91,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Mechanical Engineering Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 92,
},
{
  academicUnit: "Faculty of Technical Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Automotive Engineering Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 93,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Fashion Design and Textiles",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 94,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Catering and Hospitality",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 95,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Catering and Hospitality",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 96,
},
{
  academicUnit: "Faculty of Vocational Education",
  academicUnitType: "FACULTY",
  name: "M. Tech. Fashion Design and Textiles",
  studyLevel: "POSTGRADUATE",
  awardType: "MTECH",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 97,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "PhD Mathematics Education",
  studyLevel: "POSTGRADUATE",
  awardType: "PHD",
  studyModes: ["FULL_TIME"],
  durationYears: 3,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 98,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Mathematics Education",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 99,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Information Technology",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 100,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Information Studies",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 101,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "M.Sc. Information Technology Education",
  studyLevel: "POSTGRADUATE",
  awardType: "MSC",
  studyModes: ["WEEKEND", "SANDWICH"],
  durationYears: 1,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 102,
},
{
  academicUnit: "Faculty of Applied Sciences and Mathematics Education",
  academicUnitType: "FACULTY",
  name: "M.Ed. Mathematics Education",
  studyLevel: "POSTGRADUATE",
  awardType: "MED",
  studyModes: ["SANDWICH"],
  durationYears: null,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 103,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Business Management",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 104,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "M. Phil. Accounting",
  studyLevel: "POSTGRADUATE",
  awardType: "MPHIL",
  studyModes: ["FULL_TIME", "WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 105,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "MBA Accounting",
  studyLevel: "POSTGRADUATE",
  awardType: "MBA",
  studyModes: ["WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 106,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "MBA Finance",
  studyLevel: "POSTGRADUATE",
  awardType: "MBA",
  studyModes: ["WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 107,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "MBA Human Resource Management and Organisational Behaviour",
  studyLevel: "POSTGRADUATE",
  awardType: "MBA",
  studyModes: ["WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 108,
},
{
  academicUnit: "Faculty of Business Education",
  academicUnitType: "FACULTY",
  name: "MBA Marketing",
  studyLevel: "POSTGRADUATE",
  awardType: "MBA",
  studyModes: ["WEEKEND"],
  durationYears: 2,
  sourceUrl: "https://usted.edu.gh/wp-content/uploads/2026/05/USTED_Postgraduate_Programmes_2026-2027_Aacademic_Year.pdf",
  sortOrder: 109,
}
] as const

async function main() {
  console.log(`Seeding ${USTED_KUMASI_PROGRAMMES.length} USTED Kumasi academic programmes...`)

  for (const programme of USTED_KUMASI_PROGRAMMES) {
    await db.academicProgramme.upsert({
      where: {
        name_academicUnit_campus: {
          name: programme.name,
          academicUnit: programme.academicUnit,
          campus: "KUMASI",
        },
      },
      update: {
        academicUnitType: programme.academicUnitType,
        studyLevel: programme.studyLevel,
        awardType: programme.awardType,
        studyModesJson: JSON.stringify(programme.studyModes),
        durationYears: programme.durationYears,
        sourceAcademicYear: "2026/2027",
        sourceUrl: programme.sourceUrl,
        sortOrder: programme.sortOrder,
        active: true,
      },
      create: {
        name: programme.name,
        academicUnit: programme.academicUnit,
        academicUnitType: programme.academicUnitType,
        campus: "KUMASI",
        studyLevel: programme.studyLevel,
        awardType: programme.awardType,
        studyModesJson: JSON.stringify(programme.studyModes),
        durationYears: programme.durationYears,
        sourceAcademicYear: "2026/2027",
        sourceUrl: programme.sourceUrl,
        sortOrder: programme.sortOrder,
        active: true,
      },
    })
  }

  console.log("USTED Kumasi academic programme seed complete.")
}

main()
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
